### ISSUE TITLE
Cannot translate field label PROMOTION CATEGORY

### ISSUE THREAD

**Issue by modreoci** [solidusio-contrib/solidus_i18n#13]
I tried all the ways to find out how but I haven't succeeded.
![promotion_category](https://cloud.githubusercontent.com/assets/10616435/12533592/17297b56-c235-11e5-91b4-725ce72f7c30.png)

**Comment by tvdeyen** [comment]
Sorry, I am not able to reproduce, please provide more infos. What view are we talking about?

**Comment by modreoci** [comment]
It is on the image... screen is on route /admin/promotions

**Comment by Murph33** [comment]
So the line responsible for that has changed since you created this issue.  
https://github.com/solidusio/solidus/commit/224fb49282da0de072f3d489f1952420529efc4a#diff-4ec9b063643b93e98ae09101b2ea4f26R43

Please let us know if you're still having an issue or if we can mark this as resolved.  The model_name of Spree::PromotionCategory is now what is being displayed there.  Thanks

**Comment by tvdeyen** [comment]
@modreoci can you confirm that this is fixed with latest version?

**Comment by mamhoff** [comment]
This should be fixed, and we haven't heard back. Closing.
